packages:
  - 'apps/*'
  - 'packages/*'

nodeLinker: hoisted

allowBuilds:
  msgpackr-extract: true
  esbuild: true
  '@firebase/util': true
  protobufjs: true
  re2: true

minimumReleaseAgeExclude:
  - '@react-navigation/bottom-tabs@7.17.2'
  - '@react-navigation/elements@2.9.22'
