export function generateInspectionPdfHtml(inspection: {
  driverName: string;
  truckNumber: string;
  trailerNumber: string | null;
  status: string;
  createdAt: string;
  sections: Array<{
    title: string;
    items: Array<{ name: string; status: string | null; notes?: string }>;
  }>;
  signatureUrl?: string;
}): string {
  const sectionsHtml = inspection.sections
    .map(
      (section) => `
    <div class="section">
      <h3>${section.title}</h3>
      <table>
        <tr><th>Item</th><th>Status</th><th>Notes</th></tr>
        ${section.items
          .map(
            (item) => `
          <tr>
            <td>${item.name}</td>
            <td class="${item.status === 'fail' ? 'fail' : 'pass'}">${item.status === 'fail' ? 'FAIL' : 'PASS'}</td>
            <td>${item.notes || ''}</td>
          </tr>`
          )
          .join('')}
      </table>
    </div>`
    )
    .join('');

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; color: #131317; }
    h1 { color: #006591; font-size: 28px; }
    h2 { color: #3e4851; font-size: 16px; margin-top: 0; }
    .badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-weight: bold; font-size: 12px; }
    .badge-pass { background: rgba(0,180,255,0.2); color: #006591; }
    .badge-fail { background: rgba(147,0,10,0.2); color: #93000a; }
    .section { margin: 24px 0; }
    .section h3 { text-transform: uppercase; font-size: 13px; color: #87929c; letter-spacing: 1px; }
    table { width: 100%; border-collapse: collapse; }
    th, td { border: 1px solid #3e4851; padding: 8px 12px; text-align: left; font-size: 14px; }
    th { background: #1b1b1f; color: #e4e1e7; }
    .pass { color: #006591; font-weight: bold; }
    .fail { color: #93000a; font-weight: bold; }
    .signature { margin-top: 32px; }
    .signature img { max-width: 300px; border: 1px solid #3e4851; }
    .meta { margin-bottom: 24px; }
  </style>
</head>
<body>
  <h1>Pre-Trip Inspection Report</h1>
  <h2>Silver Crown Global</h2>
  <div class="meta">
    <p><strong>Driver:</strong> ${inspection.driverName}</p>
    <p><strong>Truck:</strong> ${inspection.truckNumber}${inspection.trailerNumber ? ` &bull; <strong>Trailer:</strong> ${inspection.trailerNumber}` : ''}</p>
    <p><strong>Date:</strong> ${new Date(inspection.createdAt).toLocaleString()}</p>
    <p><span class="badge ${inspection.status === 'PASS' ? 'badge-pass' : 'badge-fail'}">${inspection.status}</span></p>
  </div>
  ${sectionsHtml}
  ${
    inspection.signatureUrl
      ? `<div class="signature"><h3>Driver Signature</h3><img src="${inspection.signatureUrl}" alt="Signature" /></div>`
      : ''
  }
  <p style="margin-top:40px;font-size:11px;color:#87929c;">FMCSA Pre-Trip Inspection &bull; Generated by Silver Crown PTI</p>
</body>
</html>`;
}
